#!/usr/bin/env php
<?php # (jEdit options) :folding=explicit:collapseFolds=1:
/*****************************************************************************
INPUTS / SWITCHES (via $_SERVER['argv']):
    inFile           a file ending in '.pdb'

OUTPUTS / RESULTS:
    Creates a .kin file the C-Beta deviation "bullseye" distribution for the structure

*****************************************************************************/
// EVERY *top-level* page must start this way:
// 1. Define its relationship to the root of the MolProbity installation.
// Pages in subdirectories of lib/ or public_html/ will need more "/.." 's.
    if(!defined('MP_BASE_DIR')) define('MP_BASE_DIR', realpath(dirname(__FILE__).'/..'));
// 2. Include core functionality - defines constants, etc.
    require_once(MP_BASE_DIR.'/lib/core.php');
    require_once(MP_BASE_DIR.'/lib/visualize.php');
// 3. Restore session data. If you don't want to access the session
// data for some reason, you must call mpInitEnvirons() instead.
    mpInitEnvirons();       // use std PATH, etc.
    //mpStartSession(true);   // create session dir
// 5. Set up reasonable values to emulate CLI behavior if we're CGI
    set_time_limit(0); // don't want to bail after 30 sec!
// 6. Unlimited memory for processing large files
    ini_set('memory_limit', -1);

#{{{ a_function_definition - sumary_statement_goes_here
############################################################################
/**
* Documentation for this function.
*/
//function someFunctionName() {}
#}}}########################################################################

// First argument is the name of this script...
if(is_array($_SERVER['argv']))
    if(count($_SERVER['argv']) == 1) die("No input file given\n");
    else foreach(array_slice($_SERVER['argv'], 1) as $arg)
    {
        if(!isset($inFile))      $inFile = $arg;
        else                    die("Too many or unrecognized arguments: '$arg'\n");
    }
else die("Something went profoundly wrong with the commandline.\n");

if(!endsWith($inFile, ".pdb")) die("'$inFile' is not a .pdb file.\n");
if(!is_file($inFile)) die("'$inFile' is not a file that could be found.\n");

$inpath = $inFile;
$outfile = basename($inFile,".pdb")."-cbetadev.kin";

#From lib/visualize.makeCbetaDevPlot()
    exec("molprobity.cbetadev output=bullseye $inpath > $outfile");

echo("Created kinemage file: $outfile\n");
############################################################################
// Clean up and go home
#mpDestroySession(); // only call this if we created one
?>
