#!/usr/bin/env php
<?php # (jEdit options) :folding=explicit:collapseFolds=1:
/*****************************************************************************
    Processes a directory full of PDB files non-recursively and outputs
    a list of all the Ramachanadran scores

 -> We assume all files already have H's added! <-

INPUTS (via $_SERVER['argv']):
    the path to a directory; *.pdb will be processed

OUTPUTS:

*****************************************************************************/
// EVERY *top-level* page must start this way:
// 1. Define it's relationship to the root of the MolProbity installation.
// Pages in subdirectories of lib/ or public_html/ will need more "/.." 's.
    if(!defined('MP_BASE_DIR')) define('MP_BASE_DIR', realpath(dirname(__FILE__).'/..'));
// 2. Include core functionality - defines constants, etc.
    require_once(MP_BASE_DIR.'/lib/core.php');
    require_once(MP_BASE_DIR.'/lib/model.php');
    require_once(MP_BASE_DIR.'/lib/analyze.php');
    require_once(MP_BASE_DIR.'/lib/visualize.php');
// 3. Restore session data. If you don't want to access the session
// data for some reason, you must call mpInitEnvirons() instead.
    mpInitEnvirons();       // use std PATH, etc.
    //mpStartSession(true);   // create session dir
// 5. Set up reasonable values to emulate CLI behavior if we're CGI
    set_time_limit(0); // don't want to bail after 30 sec!

#{{{ a_function_definition - sumary_statement_goes_here
############################################################################
/**
* Documentation for this function.
*/
//function someFunctionName() {}
#}}}########################################################################

# MAIN - the beginning of execution for this page
############################################################################
// First argument is the name of this script...
$optBonds    = true;
$optSuitename = false;
$optPuckana = false;
$optRNA      = false;
if(is_array($_SERVER['argv'])) foreach(array_slice($_SERVER['argv'], 1) as $arg)
{
//     echo ";$arg;\n";
    if($arg == '-bonds')           $optBonds    = true;
    elseif($arg == '-suitename')
    {
        $optSuitename = true;
        $optBonds     = false;
        $optPuckana   = false;
    }
    elseif($arg == '-pucker_analysis')
    {
        $optPuckana   = true;
        $optSuitename = false;
        $optBonds     = false;
    }
    elseif(endsWith($arg, ".pdb")) $pdbFile = $arg;
}
if ($optBonds === true && $optSuitename === true) {
    die("Cannot do bonds and suitename simultaneously. Please choose one \n");
}
if(! isset($pdbFile))
    die("Must provide at least one PDB file on the command line!\n");

// analyze PDB provided

if(is_file($pdbFile) && endsWith($pdbFile, ".pdb"))
{
    mpStartSession(true);
    $id = addModelOrEnsemble(
        $pdbFile,
        basename($pdbFile),
        false,
        true,
        true,
        false);

    $filename = basename($pdbFile);
    $model   =& $_SESSION['models'][$id];
    $pdbFile = $_SESSION['dataDir'].'/'.MP_DIR_MODELS."/$model[pdb]";
    $rawDir  = $_SESSION['dataDir'].'/'.MP_DIR_RAWDATA;
    if(!file_exists($rawDir)) mkdir($rawDir, 0777);
    if($optBonds)
    {
        $outfile = "$rawDir/$model[prefix]bonds.data";
        runValidationReport($pdbFile, $outfile, $model['stats']['use_cdl']);
        $vrProteinA = loadValidationAngleReport($outfile,"protein");
        $vrProteinL = loadValidationBondReport($outfile,"protein");
        $vrRNAa = loadValidationAngleReport($outfile,"rna");
        $vrRNAl = loadValidationBondReport($outfile,"rna");
        echo "resName:type:measure:value:sigma:angCount:outCount\n";
        foreach($vrProteinA as $vr)
            echo "$vr[resName]:$vr[type]:$vr[measure]:$vr[value]:$vr[sigma]:$vr[angCount]:$vr[outCount]\n";
        foreach($vrProteinL as $vr)
            echo "$vr[resName]:$vr[type]:$vr[measure]:$vr[value]:$vr[sigma]:$vr[bondCount]:$vr[outCount]\n";
        foreach($vrRNAa as $vr)
            echo "$vr[resName]:$vr[type]:$vr[measure]:$vr[value]:$vr[sigma]:$vr[angCount]:$vr[outCount]\n";
        foreach($vrRNAl as $vr)
            echo "$vr[resName]:$vr[type]:$vr[measure]:$vr[value]:$vr[sigma]:$vr[bondCount]:$vr[outCount]\n";
    }
    if($optSuitename)
    {
        $outfile = "$rawDir/$model[prefix]suites.data";
        runSuitenameReport($pdbFile, $outfile);
        $snreport = loadSuitenameReport($outfile);
        if(empty($snreport)) die("Empty array: Are you sure there is RNA in the file?\n");
        echo "resName:conformer:suiteness:bin:triage:isOutlier\n";
        foreach($snreport as $vr)
            echo "$vr[resName]:$vr[conformer]:$vr[suiteness]:$vr[bin]:$vr[triage]:$vr[isOutlier]\n";
    }
    if($optPuckana)
    {
        $outfile = "$rawDir/$model[prefix]pucker.data";
        runBasePhosPerp($pdbFile, $outfile);
        $ppreport = loadBasePhosPerp($outfile);
        if(empty($ppreport)) die("Empty array: Are you sure there is RNA in the file?\n");
        echo "resType:chainID:resNum:insCode:altloc:Pdist5:Pdist3:delta:deltaOut:epsilon:epsilonOut:outlier\n";
        foreach($ppreport as $vr)
            echo "$vr[resType]:$vr[chainID]:$vr[resNum]:$vr[insCode]:$vr[altloc]:$vr[Pdist5]:$vr[Pdist3]:$vr[delta]:$vr[deltaOut]:$vr[epsilon]:$vr[epsilonOut]:$vr[outlier]\n";
    }
    mpDestroySession();
} else {
    die("File must have a \"pdb\" extension.\n");
}
############################################################################
// Clean up and go home
?>
